import React, {useEffect, useMemo, useRef, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Moon, Sun, Link, Play, RotateCcw, Check, ChevronLeft, ChevronRight, Captions, Volume2, Sparkles, Keyboard, CircleAlert, SkipBack, SkipForward, Eye, MonitorPlay, FileVideo, Download} from 'lucide-react'
import './styles.css'

const sample = [
  ['Chase real dopamine.', 0],
  ['Go for the run. Go outside.', 3],
  ['Talk to a friend. Journal, meditate.', 5],
  ['Read. Go to the gym. Chase real dopamine.', 8],
  ["I was distracted all the time. I knew exactly what I had to do.", 16],
  ['Actually train your brain to enjoy doing the hard things.', 22],
  ['And healthy productive habits stop feeling forced.', 30],
].map(([text,start], i)=>({id:i+1,text,start,duration:6}))

const normalize = (s) => s.toLowerCase().replace(/[^a-z0-9]/gi,'')
const videoId = (url) => { try { const u=new URL(url); return u.searchParams.get('v') || u.pathname.split('/').filter(Boolean).pop() } catch { return '' } }
const time = s => `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`
const MAX_SENTENCE=110
const srtTime=s=>{s=Math.max(0,s);return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')},${String(Math.round((s-Math.floor(s))*1000)).padStart(3,'0')}`}
const parseTimestamp=t=>{const a=t.trim().match(/^(\d+):(\d{2}):(\d{2})[.,](\d{3})$/);if(a)return +a[1]*3600+ +a[2]*60+ +a[3]+ +a[4]/1000;const b=t.trim().match(/^(\d+):(\d{2})[.,](\d{3})$/);if(b)return +b[1]*60+ +b[2]+ +b[3]/1000;return 0}
const parseCueFile=text=>{text=text.replace(/^\uFEFF/,'').replace(/\r/g,'');const cues=[],lines=text.split('\n');let i=0;while(i<lines.length){let line=lines[i].trim();if(!line){i++;continue}if(/^WEBVTT/.test(line)){i++;continue}if(/^\d+$/.test(line)){i++;continue}if(/^(NOTE|STYLE|REGION)/.test(line)){while(i<lines.length&&lines[i].trim()!=='')i++;i++;continue}if(line.includes('-->')){const m=line.match(/([\d:,.]{2,})\s*-->\s*([\d:,.]{2,})/);if(m){const start=parseTimestamp(m[1]),end=parseTimestamp(m[2]);const cueLines=[];i++;while(i<lines.length&&lines[i].trim()!==''){cueLines.push(lines[i].trim());i++}const text=cueLines.join(' ').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g,' ').trim();if(text)cues.push({text,start,duration:Math.max(0,end-start)});continue}}i++}return cues}
const splitRow=(text,rowStart,rowDuration)=>{const segments=[];let last=0;const re=/[.!?]+["']?/g;let m;while((m=re.exec(text))){segments.push(text.slice(last,m.index+m[0].length).trim());last=m.index+m[0].length}const tail=text.slice(last).trim();if(tail)segments.push(tail);const segs=segments.filter(Boolean);const total=segs.reduce((n,s)=>n+s.length,0)||1;const out=[];let t=rowStart;for(let i=0;i<segs.length;i++){const start=i===0?rowStart:t;const dur=rowDuration*segs[i].length/total;out.push({text:segs[i],start,duration:dur});t=start+dur}return out}
const buildSentences=cues=>{const sentences=[];let buffer=[];const push=text=>{if(!text)return;sentences.push({id:sentences.length+1,text,start:Math.round(buffer[0].start*100)/100,duration:Math.round(Math.max(0,buffer[buffer.length-1].end-buffer[0].start)*100)/100})};const flush=()=>{if(!buffer.length)return;const text=buffer.map(b=>b.text).join(' ').trim();if(text)push(text);buffer=[]};const append=(seg,segStart,segEnd)=>{buffer.push({text:seg,start:segStart,end:segEnd});const joined=buffer.map(b=>b.text).join(' ');if(joined.length<=MAX_SENTENCE)return;const boundaries=[...joined.matchAll(/[.!?,]\s+/g)].map(m=>m.index);const candidates=boundaries.filter(b=>b<=MAX_SENTENCE);if(candidates.length){const b=Math.max(...candidates);push(joined.slice(0,b+1).trimEnd());buffer=[{text:joined.slice(b+1).trimStart(),start:segStart,end:segEnd}];return}const space=joined.lastIndexOf(' ',MAX_SENTENCE+1);if(space>joined.length*0.5){push(joined.slice(0,space).trim());buffer=[{text:joined.slice(space).trim(),start:segStart,end:segEnd}];return}flush()};for(const cue of cues){const text=cue.text.replace(/\[[^\]]*\]/g,'').replace(/>>/g,' ').replace(/\s+/g,' ').trim();if(!text)continue;for(const seg of splitRow(text,cue.start,cue.duration)){const s=seg.start,e=seg.start+seg.duration;if(/[.!?]["']?$/.test(seg.text)){append(seg.text,s,e);flush()}else append(seg.text,s,e)}}flush();return sentences}

function App(){
  const [dark,setDark]=useState(true), [url,setUrl]=useState('https://www.youtube.com/watch?v=3NYgcQFhZCI&t=103s'), [sentences,setSentences]=useState(sample), [current,setCurrent]=useState(0), [typed,setTyped]=useState(''), [wrongAt,setWrongAt]=useState(-1), [loading,setLoading]=useState(false), [error,setError]=useState(''), [ignorePunctuation,setIgnorePunctuation]=useState(true), [completed,setCompleted]=useState([]), [mode,setMode]=useState('youtube'), [mediaUrl,setMediaUrl]=useState(''), [mediaName,setMediaName]=useState(''), [captionText,setCaptionText]=useState(''), [captionName,setCaptionName]=useState(''), [transcribing,setTranscribing]=useState(false), [transProgress,setTransProgress]=useState(0), [started,setStarted]=useState(false), [debugLog,setDebugLog]=useState([])
  const player=useRef(null), apiPlayer=useRef(null), stopTimer=useRef(null), boundaryTimer=useRef(null), mistakeTimer=useRef(null), endAt=useRef(null), input=useRef(null), localVideo=useRef(null), localUrlRef=useRef(null), mediaFile=useRef(null), videoPlaying=useRef(false), manualCaptionsRef=useRef(false), transcribingRef=useRef(false), whisperWorker=useRef(null)
  const [modelReady,setModelReady]=useState(false)

  useEffect(()=>{const w=new Worker(new URL('./whisper.worker.js',import.meta.url),{type:'module'});whisperWorker.current=w;w.onmessage=e=>{if(e.data.status==='progress'&&e.data.phase==='load'&&e.data.progress>=1)setModelReady(true)};w.postMessage({preload:true,model:'Xenova/whisper-tiny',quantized:true})},[])
 const active=sentences[current], id=videoId(url)
 const expected=ignorePunctuation?normalize(active?.text||''):(active?.text||'').toLowerCase().replace(/\s/g,'')
 const actual=typed.toLowerCase().replace(/\s/g,'')
 const isCorrect=actual===expected && !!actual
 const matchingCount=useMemo(()=>{let n=0; while(n<actual.length && n<expected.length && actual[n]===expected[n])n++; return n},[actual,expected])
 const progress=Math.round((completed.length/sentences.length)*100)
 const words = useMemo(()=>{let position=0; const isTypeable=char=>ignorePunctuation?/[a-z0-9]/i.test(char):char!==' '; return (active?.text||'').split(/(\s+)/).filter(Boolean).map(chunk=>/\s/.test(chunk)?null:chunk.split('').map(char=>({char,typeable:isTypeable(char),position:isTypeable(char)?position++:-1})))},[active,ignorePunctuation])
 const stopWatching=()=>{clearTimeout(stopTimer.current);clearInterval(boundaryTimer.current)}
 const submitCharacters=(text)=>{for(const raw of text){const char=raw.toLowerCase();if(char===' ')continue;if(ignorePunctuation&&!/[a-z0-9]/i.test(char))continue;setTyped(value=>{if(char===expected[value.length])return value+raw;clearTimeout(mistakeTimer.current);setWrongAt(value.length);mistakeTimer.current=setTimeout(()=>setWrongAt(-1),550);return value})}}
 const showAnswer=()=>{if(!active)return;setTyped(ignorePunctuation?active.text.replace(/[^a-z0-9]/gi,''):active.text.toLowerCase())}
 const toggleVideo=()=>{const v=localVideo.current;if(v&&v.src){if(!videoPlaying.current){try{v.play()}catch{}}else v.pause();return}stopWatching();const p=apiPlayer.current;if(p?.getPlayerState){const st=p.getPlayerState();if(st===window.YT?.PlayerState?.PLAYING)p.pauseVideo();else if(videoPlaying.current)p.playVideo();return}const win=player.current?.contentWindow;const command=(func,args=[])=>win?.postMessage(JSON.stringify({event:'command',func,args}),'*');if(videoPlaying.current)command('pauseVideo');else command('playVideo')}
 const watchEnd=(getTime,pause)=>{clearInterval(boundaryTimer.current); if(endAt.current==null)return; let stopped=false; boundaryTimer.current=setInterval(()=>{try{if(!stopped&&getTime()>=endAt.current-.025){stopped=true;pause();setTimeout(pause,80);setTimeout(pause,200);stopWatching()}}catch{}},50)}
 const playAt=(index=current)=>{ const line=sentences[index]; if(!line)return; stopWatching(); const nextStart=sentences[index+1]?.start; const playStart=Math.max(0,Number(line.start)-.2); const realEnd=nextStart!=null?Number(nextStart):Number(line.start)+Math.max(1,Number(line.duration)||3); const end=Math.min(realEnd,Number(line.start)+Math.max(1,Number(line.duration)||3))+.02; endAt.current=end; const v=localVideo.current; if(v&&v.src){const play=()=>{try{v.currentTime=playStart;v.play();watchEnd(()=>v.currentTime,()=>{try{v.pause()}catch{}});stopTimer.current=setTimeout(()=>{try{v.pause()}catch{}},Math.max(1,end-playStart+.3)*1000)}catch{}};if(v.readyState>=1)play();else v.addEventListener('loadeddata',play,{once:true});return} const p=apiPlayer.current; if(p?.seekTo){p.pauseVideo();p.seekTo(playStart,false);p.playVideo();watchEnd(()=>p.getCurrentTime(),()=>{try{p.pauseVideo()}catch{}});stopTimer.current=setTimeout(()=>{try{p.pauseVideo()}catch{}},Math.max(1,end-playStart+.3)*1000);return} const win=player.current?.contentWindow; const command=(func,args=[])=>win?.postMessage(JSON.stringify({event:'command',func,args}),'*'); command('pauseVideo');command('seekTo',[playStart,true]);setTimeout(()=>command('playVideo'),80);stopTimer.current=setTimeout(()=>command('pauseVideo'),Math.max(1,end-playStart+.3)*1000) }
 const move=(index, autoplay=true)=> {const next=Math.max(0,Math.min(index,sentences.length-1)); stopWatching();clearTimeout(mistakeTimer.current);setWrongAt(-1);setCurrent(next);setTyped(''); if(autoplay)setTimeout(()=>playAt(next),180); setTimeout(()=>input.current?.focus(),220)}
 useEffect(()=>{move(0,false)},[sentences])
 useEffect(()=>{window.scrollTo(0,0)},[])
 useEffect(()=>{const v=localVideo.current;if(!v||mode!=='local')return;const onPlay=()=>videoPlaying.current=true;const onPause=()=>videoPlaying.current=false;v.addEventListener('play',onPlay);v.addEventListener('pause',onPause);return()=>{v.removeEventListener('play',onPlay);v.removeEventListener('pause',onPause)}},[mode])
 useEffect(()=>{if(mode!=='youtube')return;const onMsg=e=>{try{const d=typeof e.data==='string'?JSON.parse(e.data):null;if(d&&d.event==='infoDelivery'&&d.info&&typeof d.info.playerState==='number')videoPlaying.current=d.info.playerState===1}catch{}};window.addEventListener('message',onMsg);return()=>window.removeEventListener('message',onMsg)},[mode])
  useEffect(()=>{if(!started||mode!=='youtube')return;const init=()=>{if(!window.YT?.Player||apiPlayer.current)return;apiPlayer.current=new window.YT.Player('youtube-player',{events:{onStateChange:event=>{videoPlaying.current=event.data===window.YT.PlayerState.PLAYING;if(event.data===window.YT.PlayerState.PLAYING)watchEnd(()=>apiPlayer.current?.getCurrentTime?.()??0,()=>{try{apiPlayer.current?.pauseVideo()}catch{}})}}})};if(window.YT?.Player)init();else{const existing=document.querySelector('script[data-youtube-api]');if(existing)existing.addEventListener('load',init);else{const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.dataset.youtubeApi='true';script.onload=init;document.head.appendChild(script)}return()=>{clearInterval(boundaryTimer.current);clearTimeout(stopTimer.current);apiPlayer.current=null}}},[started,mode])
 useEffect(()=>{ const hotkey=e=>{const focused=document.activeElement;const editingElsewhere=focused&&focused!==input.current&&['INPUT','TEXTAREA'].includes(focused.tagName);if(editingElsewhere)return;if(e.key==='Tab'){e.preventDefault();playAt();return} if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();setTyped(t=>{const c=expected[t.length];return c?t+c:t});return} if(e.key==='Enter'){e.preventDefault();if(isCorrect)move(current+1);return} if(e.key==='Backspace'){e.preventDefault();setTyped(value=>value.slice(0,-1));setWrongAt(-1);return} if(e.ctrlKey||e.metaKey||e.altKey||e.key.length!==1||e.key===' ')return;e.preventDefault();submitCharacters(e.key)};window.addEventListener('keydown',hotkey);return()=>window.removeEventListener('keydown',hotkey)},[current,isCorrect,sentences,expected])
 useEffect(()=>{if(isCorrect&&!completed.includes(active.id)){setCompleted(v=>[...v,active.id]);}},[isCorrect])
  const fetchCaptions=async(e)=>{e.preventDefault();setError('');if(!videoId(url)){setError('Paste a valid YouTube URL to begin.');return false}setLoading(true);try{const res=await fetch(`/api/transcript?url=${encodeURIComponent(url)}`); const data=await res.json();if(!res.ok)throw Error(data.detail);if(!data.sentences?.length)throw Error('No captions found for this video. Please try a video with CC.');setCompleted([]);setSentences(data.sentences);return true}catch(err){setError(err.message||'No captions found for this video. Please try a video with CC.');return false}finally{setLoading(false)}}
  const beginYouTube=async e=>{if(await fetchCaptions(e))setStarted(true)}
  const pickMedia=e=>{const f=e.target.files?.[0];if(!f)return;if(localUrlRef.current)URL.revokeObjectURL(localUrlRef.current);const u=URL.createObjectURL(f);localUrlRef.current=u;mediaFile.current=f;setMediaUrl(u);setMediaName(f.name);manualCaptionsRef.current=false;setCaptionText('');setCaptionName('');setError('')}
  const pickCaptions=e=>{const f=e.target.files?.[0];if(!f)return;manualCaptionsRef.current=true;const r=new FileReader();r.onload=()=>{setCaptionText(r.result||'');setCaptionName(f.name);setError('')};r.readAsText(f)}
  const enterLocalPractice=()=>{try{localVideo.current?.pause()}catch{}const cues=parseCueFile(captionText);const s=buildSentences(cues);if(!s.length)throw Error('No captions found in this file. Use a .srt or .vtt file.');setCompleted([]);setSentences(s);setStarted(true);return true}
  const startLocal=async e=>{e.preventDefault();if(!mediaUrl){setError('Add an audio or video file first.');return false}setError('');if(!captionText){if(transcribingRef.current)return false;setLoading(true);const ok=await transcribe();setLoading(false);if(ok){setStarted(true);return true}return false}setLoading(true);try{return enterLocalPractice()}catch(err){setError(err.message||'Could not read captions. Use a .srt or .vtt file.');return false}finally{setLoading(false)}}
  const decodeAudio=file=>new Promise(async(resolve,reject)=>{try{const AC=window.AudioContext||window.webkitAudioContext;const ctx=new AC();const buf=await file.arrayBuffer();const ab=await ctx.decodeAudioData(buf);let audio;if(ab.numberOfChannels===1)audio=ab.getChannelData(0);else{const chs=[];for(let i=0;i<ab.numberOfChannels;i++)chs.push(ab.getChannelData(i));audio=new Float32Array(ab.length);for(let i=0;i<ab.length;i++){let s=0;for(const c of chs)s+=c[i];audio[i]=s/chs.length}}ctx.close();const srcRate=ab.sampleRate;const targetRate=16000;if(srcRate!==targetRate){const ratio=srcRate/targetRate;const newLen=Math.round(audio.length/ratio);const resampled=new Float32Array(newLen);for(let i=0;i<newLen;i++){const srcIdx=i*ratio;const idx=Math.floor(srcIdx);const frac=srcIdx-idx;resampled[i]=idx+1<audio.length?audio[idx]*(1-frac)+audio[idx+1]*frac:audio[idx]}audio=resampled}resolve({audio,sampleRate:16000})}catch(e){reject(e)}})
 const transcribe=async()=>{const file=mediaFile.current;if(!file||transcribingRef.current){setError(file?'':'Select a video or audio file first.');return false}transcribingRef.current=true;setError('');setTranscribing(true);setTransProgress(0);setDebugLog([]);let applied=false;const log=(msg)=>setDebugLog(v=>[...v,Date.now()+': '+msg]);try{if(!whisperWorker.current)whisperWorker.current=new Worker(new URL('./whisper.worker.js',import.meta.url),{type:'module'});const worker=whisperWorker.current;const result=await new Promise(async resolve=>{const onMsg=e=>{const m=e.data;if(m.status==='progress'){if(m.phase==='load'){setTransProgress(-1);log('loading model...')}else if(m.phase==='transcribe'){const p=Math.round((m.progress||0)*100);setTransProgress(p)}}else if(m.status==='complete'){log('done: '+(m.data?.chunks?.length||0)+' chunks');worker.removeEventListener('message',onMsg);resolve({chunks:m.data?.chunks||[],text:m.data?.text||''})}else if(m.status==='error'){log('error: '+(m.data?.message||'unknown'));worker.removeEventListener('message',onMsg);resolve({error:m.data?.message||'Transcription failed'})}};worker.addEventListener('message',onMsg);try{const {audio,sampleRate}=await decodeAudio(file);log('audio: '+audio.length+' samples, '+Math.round(audio.length/16000)+'s');worker.postMessage({audio,model:'Xenova/whisper-tiny',quantized:true},[audio.buffer])}catch(err){resolve({error:err.message||'Could not decode this audio file.'})}});if(result.error)throw Error(result.error);const chunks=result.chunks||[];let prevEnd=0;const cues=chunks.map(c=>{const s=c.timestamp?.[0]??prevEnd;const e=c.timestamp?.[1]??s+1;prevEnd=e;return {text:c.text,start:Math.round(s*100)/100,duration:Math.round(Math.max(0,e-s)*100)/100}});const s=buildSentences(cues);if(!s.length)throw Error('No speech detected in this file.');const srt=s.map((x,i)=>`${i+1}\n${srtTime(x.start)} --> ${srtTime(x.start+x.duration)}\n${x.text}\n`).join('\n');setCaptionText(srt);setCaptionName('auto-generated.srt');setCompleted([]);setSentences(s);applied=true}catch(err){setError(err.message||'Could not transcribe this file.')}finally{setTranscribing(false);transcribingRef.current=false}return applied}
 const downloadSrt=()=>{if(!captionText)return;const blob=new Blob([captionText],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(captionName||'captions.srt').replace(/\.[^.]*$/,'')+'.srt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
  const startDisabled=loading||!mediaUrl
  const startTitle=!mediaUrl?'Add an audio or video file first':!captionText?(transcribing?'Transcribing — captions are coming…':'Start practice — we will transcribe the audio automatically'):'Start practice'
   const localHint=transcribing?(transProgress<0?'Loading whisper model… this may take a few seconds.':`Transcribing audio… ${transProgress}%`)
   :mediaName&&!captionText?'No captions yet — press Start practice and we will transcribe the audio automatically. Or add your own .srt/.vtt file.'
   :captionText?'Captions ready — press Start practice to begin.'
   :'Add an audio or video file — we will transcribe it into captions when you press Start, or add your own .srt/.vtt file.'
  const LocalControls=()=>(
   <>
    <label className="file"><FileVideo size={16}/><span>{mediaName||'Audio / video file'}</span><input type="file" accept="video/*,audio/*" onChange={pickMedia} aria-label="Choose audio or video file"/></label>
    <label className="file"><Captions size={16}/><span>{captionName||'Caption file (.srt / .vtt)'}</span><input type="file" accept=".srt,.vtt,text/plain,text/vtt" onChange={pickCaptions} aria-label="Choose captions file"/></label>
    {captionText&&<button className="download" type="button" onClick={downloadSrt} aria-label="Download the generated .srt file" title="Download .srt file"><Download size={15}/></button>}
    <button disabled={startDisabled} title={startTitle}>{loading?transcribing?`Transcribing ${transProgress>0?transProgress+'% ':''}…`:'Loading…':'Start practice'}</button>
   </>
  )
  return <main className={dark?'app dark':'app'}>
   {!started?<div className="start">
    <button className="icon theme-toggle" onClick={()=>setDark(!dark)} aria-label={dark?'Switch to light theme':'Switch to dark theme'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button>
    <div className="start-logo"><span className="mark"><Captions size={22}/></span><b>Echo<span>Type</span></b></div>
    <h1 className="start-title">Practice listening,<br/><em>one sentence at a time.</em></h1>
    <p className="start-sub">Turn any subtitled YouTube lesson or your own video into focused, active listening practice. Type what you hear — the letters reveal themselves as you go.</p>
    <div className="start-cards">
     <button type="button" aria-pressed={mode==='youtube'} className={mode==='youtube'?'src-card active':'src-card'} onClick={()=>setMode('youtube')}><MonitorPlay size={26}/><b>YouTube video</b><span>Paste a link — we fetch the captions.</span></button>
     <button type="button" aria-pressed={mode==='local'} className={mode==='local'?'src-card active':'src-card'} onClick={()=>setMode('local')}><FileVideo size={26}/><b>Local file</b><span>Video/audio + .srt/.vtt captions, or transcribe automatically.</span></button>
    </div>
    {mode==='youtube'
     ?<form className="start-form" onSubmit={beginYouTube}><Link size={17}/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste a YouTube URL..." aria-label="YouTube URL" spellCheck="false" autoComplete="off"/><button disabled={loading||!videoId(url)}>{loading?'Loading...':'Start practice'}</button></form>
      :<form className="start-form local" onSubmit={startLocal}><LocalControls/><div className="local-hint">{localHint}</div>{debugLog.length>0&&<div className="debug-log">{debugLog.slice(-12).map((l,i)=><div key={i}>{l}</div>)}</div>}</form>}
    {error&&<div className="notice" role="alert"><CircleAlert size={18}/>{error}</div>}
    <button className="start-skip" onClick={()=>setStarted(true)}>Just browsing? Skip to the demo →</button>
   </div>
   :<>
    <header><button type="button" className="brand" onClick={()=>setStarted(false)} title="Back to start" aria-label="EchoType, back to start"><span className="mark"><Captions size={19}/></span><span>Echo<span>Type</span></span></button>{mode==='youtube'?<form onSubmit={fetchCaptions} className="url"><Link size={17}/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste a YouTube URL..." aria-label="YouTube URL" spellCheck="false" autoComplete="off"/><button disabled={loading}>{loading?'Loading...':'Start practice'}</button></form>:<div className="head-right">{captionText&&<button className="dl" onClick={downloadSrt} title="Download the transcript as an .srt file" aria-label="Download transcript"><Download size={15}/>Download Transcript</button>}</div>}<button className="icon" onClick={()=>setDark(!dark)} aria-label={dark?'Switch to light theme':'Switch to dark theme'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button></header>
  <section className="hero"><div><p className="eyebrow"><Sparkles size={15}/> LISTEN · TYPE · LEARN</p><h1>Practice listening,<br/><em>one sentence at a time.</em></h1><p className="sub">Turn any subtitled YouTube lesson into focused, active listening practice.</p></div><div className="stats"><b>{sentences.length}</b><span>sentences<br/>to master</span><div className="ring"><b>{progress}%</b><small>done</small></div></div></section>
  {error&&<div className="notice" role="alert"><CircleAlert size={18}/>{error}</div>}
  <div className="layout">
   <div className="col-left">
    <div className="player" role="group" aria-label="Video player">{mode==='local'?<video ref={localVideo} src={mediaUrl} playsInline controls preload="metadata" aria-label="Lesson video"/>:<iframe id="youtube-player" ref={player} src={`https://www.youtube.com/embed/${id||'2I0w-1VUPm4'}?enablejsapi=1&rel=0`} title="YouTube player" allow="autoplay; encrypted-media"/>}<div className="player-label"><span className="live"></span> VIDEO PLAYER</div></div>
    <aside aria-label="Lesson navigation"><div className="sidehead"><div><p className="eyebrow">YOUR LESSON</p><h3>Sentence queue</h3></div><span>{completed.length}/{sentences.length}</span></div><ul className="sentence-list">{sentences.map((s,i)=><li key={s.id}><button onClick={()=>move(i)} aria-current={i===current?'true':undefined} className={i===current?'active':completed.includes(s.id)?'done':''}><span className="number">{completed.includes(s.id)?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><div><b style={completed.includes(s.id)?{}:{filter:'blur(5px)',userSelect:'none'}}>{s.text}</b><small>{time(s.start)}</small></div><Play size={15}/></button></li>)}</ul><div className="shortcuts"><Keyboard size={17}/><div><b>Keyboard shortcuts</b><span><kbd>Tab</kbd> replay &nbsp; <kbd>Enter</kbd> replay / next &nbsp; <kbd>Space</kbd> play / pause</span></div></div></aside>
   </div>
   <div className="col-right">
    <article className="dictation" aria-label="Dictation practice"><div className="cardtop"><p className="eyebrow"><span>✍️</span> Type what you hear — letters reveal as you go</p><span className="score" aria-label={`Sentence ${current+1} of ${sentences.length}. Correct ${progress} percent.`}>{current+1} / {sentences.length} · Correct: {progress}%</span></div>
     <div className="answer-line" aria-hidden="true">{words.map((word,i)=>word===null?<span key={i} className="answer-space"/>:<span key={i} className="word-group">{word.map(({char,typeable,position},j)=>typeable?<span key={j} className={position<matchingCount?'revealed':'masked'}>{position<matchingCount?char:'•'}</span>:<span key={j} className="punct">{char}</span>)}</span>)}</div>
     <div className="typing" onClick={()=>input.current?.focus()}><div className="tile-row" aria-hidden="true">{words.map((word,i)=>word===null?<span key={i} className="word-space"/>:<span key={i} className="word-group">{word.map(({char,typeable,position},j)=>{if(!typeable)return <span key={j} className="punct">{char}</span>; const isWrong=position===wrongAt; return <span key={j} className={`tile ${position<matchingCount?'matched':''} ${position===matchingCount?'current':''} ${isWrong?'wrong':''}`}>{position<matchingCount?char:(isWrong?'×':'·')}</span>})}</span>)}</div><input ref={input} value={typed} onKeyDown={e=>{if(e.key===' ')e.preventDefault()}} onChange={e=>{const next=e.target.value.replace(/\s/g,'');if(next.length<typed.length){setTyped(next);return}submitCharacters(next.slice(typed.length))}} aria-label="Type dictation" autoComplete="off" spellCheck="false" autoCapitalize="none" autoCorrect="off" enterKeyHint="go"/></div>
     <div className="track" role="progressbar" aria-label="Lesson progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(((current + (isCorrect?1:0))/sentences.length)*100)}><i style={{width:`${((current + (isCorrect?1:0))/sentences.length)*100}%`}}/></div>
      <div className="actions"><button className="replay" onClick={showAnswer}><Eye size={17}/> Show answer</button><button className="replay" onClick={()=>setTyped(t=>{const c=expected[t.length];return c?t+c:t})}><Sparkles size={17}/> Hint</button><button className="replay" onClick={()=>playAt()}><RotateCcw size={17}/> Replay</button></div>
     <div className="sr-only" aria-live="polite" role="status">{isCorrect?`Correct! ${completed.length} of ${sentences.length} sentences done.`:''}</div>
    </article>
    <div className="lesson-controls" role="group" aria-label="Lesson controls"><button onClick={()=>move(current-1)} disabled={current===0}><SkipBack size={20}/><b>Previous</b><kbd>Ctrl</kbd></button><button onClick={()=>playAt()}><RotateCcw size={20}/><b>Listen again</b><kbd>Tab</kbd></button><button onClick={()=>move(current+1)} disabled={!isCorrect||current===sentences.length-1}><SkipForward size={20}/><b>Next</b><kbd>Enter</kbd></button></div>
   </div>
  </div>
   </>}
  </main>
}
createRoot(document.getElementById('root')).render(<App/>)
